name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
      - name: Run linters
        run: |
          pip install flake8
          flake8 .
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest -q; else echo "No tests configured"; fi
